import type { TheoryConcept } from "@/features/theory/types";

export const UNITARY_MATRICES: TheoryConcept = {
  id: "unitary-matrices",
  level: "intermediate",
  category: "linear-algebra",
  notation: "matrix",
  tags: ["unitary", "orthonormal", "eigenvalues", "unit-circle"],
  relatedConceptIds: ["inner-product", "hermitian-matrices", "spectral-theorem", "unit-roots"],

  title: {
    en: "Unitary matrices",
    es: "Matrices unitarias",
  },
  summary: {
    en: "Square complex matrices that preserve the inner product. Their eigenvalues lie on the unit circle and their columns form an orthonormal basis.",
    es: "Matrices complejas cuadradas que conservan el producto interno. Sus autovalores están en la circunferencia unidad y sus columnas forman una base ortonormal.",
  },
  learningObjectives: {
    en: [
      "State the equivalent characterisations U†U = I, UU† = I and ‖Uv‖ = ‖v‖.",
      "Verify whether a given complex matrix is unitary.",
      "Relate unitary evolution to reversibility in closed quantum systems.",
    ],
    es: [
      "Enunciar las caracterizaciones equivalentes U†U = I, UU† = I y ‖Uv‖ = ‖v‖.",
      "Verificar si una matriz compleja dada es unitaria.",
      "Relacionar la evolución unitaria con la reversibilidad en sistemas cuánticos cerrados.",
    ],
  },
  formalDefinition: {
    en: "A square matrix U ∈ ℂⁿˣⁿ is unitary if U†U = UU† = I, where U† is the conjugate transpose. Equivalently, U is invertible and U⁻¹ = U†.",
    es: "Una matriz cuadrada U ∈ ℂⁿˣⁿ es unitaria si U†U = UU† = I, donde U† es la conjugada traspuesta. Equivalentemente, U es invertible y U⁻¹ = U†.",
  },
  intuitiveExplanation: {
    en: "A unitary is an isometry of complex space: it never stretches or shrinks vectors and it preserves the angle (inner product) between them. Geometrically it is a rotation/reflection of ℂⁿ. In quantum computing every gate that is not a measurement is unitary.",
    es: "Una unitaria es una isometría del espacio complejo: nunca estira ni encoge vectores y preserva el ángulo (producto interno) entre ellos. Geométricamente es una rotación o reflexión de ℂⁿ. En computación cuántica toda puerta que no sea una medida es unitaria.",
  },
  geometricOrPhysicalInterpretation: {
    en: "Closed-system quantum evolution is generated by the Schrödinger equation and integrates to a unitary U(t) = exp(−iHt/ℏ). Reversibility of quantum logic gates is exactly the fact that U†U = I.",
    es: "La evolución cuántica de un sistema cerrado se genera con la ecuación de Schrödinger y se integra a una unitaria U(t) = exp(−iHt/ℏ). La reversibilidad de las puertas cuánticas es exactamente el hecho de que U†U = I.",
  },
  examRelevance: {
    en: "Exam questions ask you to verify the unitarity of a matrix, to combine two unitaries (the product is unitary), or to argue that eigenvalues of a unitary must satisfy |λ| = 1.",
    es: "Las preguntas de examen piden verificar la unitariedad de una matriz, combinar dos unitarias (el producto es unitario) o argumentar que los autovalores de una unitaria deben cumplir |λ| = 1.",
  },

  formulas: [
    {
      label: {
        en: "Defining property",
        es: "Propiedad de definición",
      },
      latex: "U^{\\dagger} U = U U^{\\dagger} = \\mathbb{1}",
      explanation: {
        en: "Equivalently, the columns of U form an orthonormal basis of ℂⁿ.",
        es: "Equivalentemente, las columnas de U forman una base ortonormal de ℂⁿ.",
      },
    },
    {
      label: {
        en: "Inner-product preservation",
        es: "Conservación del producto interno",
      },
      latex: "\\langle Uu, Uv \\rangle = \\langle u, v \\rangle",
      explanation: {
        en: "U†U = I yields ⟨Uu, Uv⟩ = ⟨u, U†Uv⟩ = ⟨u, v⟩.",
        es: "U†U = I implica ⟨Uu, Uv⟩ = ⟨u, U†Uv⟩ = ⟨u, v⟩.",
      },
    },
    {
      label: {
        en: "Eigenvalues lie on the unit circle",
        es: "Autovalores en la circunferencia unidad",
      },
      latex: "U |\\psi\\rangle = \\lambda |\\psi\\rangle \\Rightarrow |\\lambda| = 1",
      explanation: {
        en: "Take the norm of both sides; ‖Uψ‖ = ‖ψ‖ forces |λ| = 1.",
        es: "Toma norma a ambos lados; ‖Uψ‖ = ‖ψ‖ obliga a |λ| = 1.",
      },
    },
  ],

  workedExamples: [
    {
      title: {
        en: "Hadamard is unitary",
        es: "La Hadamard es unitaria",
      },
      statement: {
        en: "Verify that H = (1/√2) [[1, 1], [1, −1]] satisfies H†H = I.",
        es: "Verifica que H = (1/√2) [[1, 1], [1, −1]] cumple H†H = I.",
      },
      steps: [
        {
          title: {
            en: "Compute H†",
            es: "Calcula H†",
          },
          latex: "H^{\\dagger} = \\tfrac{1}{\\sqrt{2}} \\begin{bmatrix} 1 & 1 \\\\ 1 & -1 \\end{bmatrix}",
          explanation: {
            en: "H has real entries and is symmetric, so H† = Hᵀ = H.",
            es: "H tiene entradas reales y es simétrica, así que H† = Hᵀ = H.",
          },
        },
        {
          title: {
            en: "Compute the product",
            es: "Calcula el producto",
          },
          latex: "H^{\\dagger} H = \\tfrac{1}{2} \\begin{bmatrix} 1 & 1 \\\\ 1 & -1 \\end{bmatrix} \\begin{bmatrix} 1 & 1 \\\\ 1 & -1 \\end{bmatrix}",
          explanation: {
            en: "Pull the scalar prefactor to the front.",
            es: "Saca el escalar al frente.",
          },
        },
        {
          title: {
            en: "Multiply",
            es: "Multiplica",
          },
          latex: "= \\tfrac{1}{2} \\begin{bmatrix} 2 & 0 \\\\ 0 & 2 \\end{bmatrix} = \\mathbb{1}",
          explanation: {
            en: "Off-diagonal entries cancel; diagonal entries give 2/2 = 1.",
            es: "Las entradas fuera de la diagonal se cancelan; las diagonales dan 2/2 = 1.",
          },
        },
      ],
      finalAnswer: {
        en: "H†H = I, hence H is unitary (and self-inverse).",
        es: "H†H = I, luego H es unitaria (y autoinversa).",
      },
    },
  ],

  commonMistakes: {
    en: [
      "Forgetting the complex conjugate inside U†; transposing alone is not enough.",
      "Checking only U†U = I when both U†U = I and UU† = I are required in infinite dimension. (In finite dimension one implies the other.)",
      "Assuming the eigenvalues are real; they have modulus 1 but live anywhere on the unit circle.",
    ],
    es: [
      "Olvidar la conjugación compleja en U†; la mera trasposición no basta.",
      "Comprobar sólo U†U = I cuando en dimensión infinita hacen falta U†U = I y UU† = I. (En dimensión finita una implica la otra.)",
      "Asumir que los autovalores son reales; tienen módulo 1 pero pueden estar en cualquier punto de la circunferencia unidad.",
    ],
  },

  examQuestions: [
    {
      id: "unitary-q1",
      difficulty: "medium",
      statement: {
        en: "Show that the product of two unitary matrices is unitary.",
        es: "Demuestra que el producto de dos matrices unitarias es unitario.",
      },
      expectedAnswer: {
        en: "Let U and V be unitary, so U†U = I and V†V = I. Then (UV)†(UV) = V†U†UV = V†(I)V = V†V = I. The product satisfies the unitary defining identity, hence UV is unitary.",
        es: "Sean U y V unitarias, con U†U = I y V†V = I. Entonces (UV)†(UV) = V†U†UV = V†(I)V = V†V = I. El producto cumple la identidad definitoria, luego UV es unitaria.",
      },
      hints: {
        en: [
          "Use that (AB)† = B†A†.",
          "Plug into U†U = I and V†V = I and chain.",
        ],
        es: [
          "Usa que (AB)† = B†A†.",
          "Sustituye en U†U = I y V†V = I y encadena.",
        ],
      },
    },
  ],
};
